# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_preparation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default='0'),
            preserve_default=False, ),
    ]
