# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20170612_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalizedsale',
            name='product_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
