# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketsale',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='basketsale',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
